# Cloud Build configuration for automatic deployment
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/standing-set-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/standing-set-backend:latest'
      - '-f'
      - 'Dockerfile.production'
      - '.'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/standing-set-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/standing-set-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile.production'
      - './frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/standing-set-backend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/standing-set-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-backend'
    args:
      - 'run'
      - 'deploy'
      - 'standing-set-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/standing-set-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend'
    args:
      - 'run'
      - 'deploy'
      - 'standing-set-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/standing-set-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '80'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/standing-set-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/standing-set-backend:latest'
  - 'gcr.io/$PROJECT_ID/standing-set-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/standing-set-frontend:latest'

# Build timeout
timeout: '1200s'